[versions]
# Plugin
androidGradlePlugin = "8.9.1"

# DI
koin_version = "3.4.3"
koin_ksp_version = "1.2.2"
koin_androidx_compose_version = "3.4.2"


# Kotlin
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"
kotlinxCoroutines = "1.10.1"


# Android Jetpack
androidxCore = "1.15.0"
androidxLifecycle = "2.8.7"
androidxRoom = "2.6.1"

# Jetpack Compose
material3 = "1.3.1"
androidxComposeBom = "2025.03.00"
androidxActivity = "1.10.1"
androidxPaging = "3.3.6"
androidxNavigation = "2.8.9"
androidxAppCompat = "1.7.0"


# Kotlin serialisation
kotlinxSerializationJson = "1.8.0"

coil = "2.7.0"

# Permission
accompanistPermission = "0.37.0"

androidxDatastore = "1.1.4"

# Test
junit = "4.13.2"
androidxTestExt = "1.2.1"
androidxEspresso = "3.6.1"
mockk = "1.13.4"

androidxCoreSplashscreen = "1.0.1"


ktor = "3.1.0"

libphonenumber = "8.13.15"
ccp = "2.7.3"


[libraries]
# Gradle
gradle_build = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin_gradle_build = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlin
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# Android
androidx-core-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }


# Compose androidx
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material-icon = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx_material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-runtime_compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }

# Coil
coil_compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil_svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }


# Koin
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin_version" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin_ksp_version" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin_ksp_version" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin_androidx_compose_version" }

# Kotlin serialisation version
kotlin_serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Permission
permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermission" }

# DataStore
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastore" }

ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber" , version.ref = "libphonenumber" }


# Test
compose-debug-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }


[bundles]
androidx = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx"
]

#coroutines = [
#    "kotlinx-coroutines-core",
#    "kotlinx-coroutines-android"
#]

compose = [
    "androidx-compose-ui",
    "androidx_material3",
    "androidx-compose-material3-window",
    "androidx-compose-tooling",
    "androidx-compose-tooling-preview",
    "androidx-lifecycle-runtime-ktx",
    "androidx-compose-material-icon",
    "androidx-activity-compose"
]

ktor = [
    "ktor-client-core",
    "ktor-client-android",
    "ktor-client-okhttp",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "ktor-client-logging"
]

koin = [
    "koin-android",
    "koin-compose",
    "koin-annotations"
]

test = [
    "junit",
    "kotlinx-coroutines-test",
    "mockk"
]

androidTest = [
    "androidx-espresso-core",
    "androidx-ui-test-junit4",
    "androidx-junit-ktx",
]


[plugins]

project_android_application_compose = { id = "project.android.application.compose", version = "unspecified" }
project_android_application = { id = "project.android.application", version = "unspecified" }
project_android_library = { id = "project.android.library", version = "unspecified" }
project_android_library_compose = { id = "project.android.library.compose", version = "unspecified" }
project_android_feature = { id = "project.android.feature", version = "unspecified" }
project_jvm_library = { id = "project.jvm.library", version = "unspecified" }

android_application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android_library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

